--任务变量access code定义
--与C++ enum KE_PRE_DEFINED_TASK_ACCESS_CODE 保持一致

TASK_ACCESS_CODE_PET = 1;
TASK_ACCESS_CODE_MERIDIAN = 2;
TASK_ACCESS_CODE_DAILY_TASK = 3;
TASK_ACCESS_CODE_TASK_SAVEVERSION = 33557788;--记录任务变量的版本号，密码复杂点,>65535,可以阻止被客户端修改^_^
TASK_ACCESS_CODE_GUANKA_TASK = 4;--2012年6月份资料片关卡通天幻境，万剑冢日常和周常任务
TASK_ACCESS_CODE_GUTIANMENBAOXIANG = 5--古天门宝箱
TASK_ACCESS_CODE_OLYMPIC = 6 --奥运活动
TASK_ACCESS_CODE_OUTWEAR = 7 --外装显示
TASK_ACCESS_CODE_OFFLINELIVE = 8 --离线挂机
TASK_ACCESS_CODE_CHRISTMASSNOWDOWN = 9 --打雪仗功能
TASK_ACCESS_CODE_ZQBATTLE = 10 --真气战场
TASK_ACCESS_CODE_BIT_TASK = 11 --按位存取的任务变量
TASK_ACCESS_CODE_KF_BATTLE = 12 --跨服战场的
TASK_ACCESS_CODE_KUAFU_DRAG = 13 --跨服消耗药品使用
TASK_ACCESS_CODE_VIP_FEEDBACK_SYS = 14 --御街积分反馈系统
TASK_ACCESS_CODE_ENERGY_SYS = 15 --精力系统
TASK_ACCESS_CODE_DXG_MISSION = 16 --地玄宫
TASK_ACCESS_CODE_TONG_FEAST = 17 --帮会盛宴
TASK_ACCESS_CODE_MONTHLY_IB = 18 --月消费统计
TASK_ACCESS_CODE_TONG_INFO_TRANS = 19 --帮会信息定义到任务变量上
TASK_ACCESS_CODE_TONG_MELEE = 20 --帮会大乱斗
TASK_ACCESS_CODE_BIWUDAHUI = 21 --比武大会
TASK_ACCESS_CODE_ACTIVITY_KILLTASK = 22 --活动杀怪模板
TASK_ACCESS_CODE_DAILY_REGISTRATION = 23 --每日签到
TASK_ACCESS_CODE_WORLD_BOSS = 24 --世界BOSS
TASK_ACCESS_CODE_STATE_CHESS = 25 --仗剑天涯
TASK_ACCESS_CODE_VIP_CARD = 26 --武林vip令
TASK_ACCESS_CODE_LUCKY_BOX = 27 --幸运大宝箱
TASK_ACCESS_CODE_GEM_SYSTEM = 28 --宝石系统
TASK_ACCESS_CODE_EXGSVR = 29 --跨服
TASK_ACCESS_CODE_PLAYER_IB = 30 --武林功勋和剑侠点数
TASK_ACCESS_CODE_SLT = 31 --四灵试炼
TASK_ACCESS_CODE_VJW = 32 --越南收费激活武尊
TASK_ACCESS_CODE_EYT = 33 --恩怨台战场
TASK_ACCESS_CODE_KFTJL = 34 -- 跨服消耗天骄令